CREATE TABLE IF NOT EXISTS `Camden` (
    `id` INT NOT NULL AUTO_INCREMENT
    ,`date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ,`dayOrNight` TINYINT(1) default 1
    ,`email` VARCHAR(100) NOT NULL
    ,`password` VARCHAR(60) NOT NULL
    ,`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    ,PRIMARY KEY (`id`)
    ,UNIQUE (`email`)
)